version: '3.3'
services:
    cameraevents:
        volumes:
            - '/volume1/docker/cameraevents/userdb.db:/app/userdb.db'
            - '/volume1/docker/cameraevents/logs/:/app/logs/'
        ports:
            - '18088:80'
        network_mode: web
        container_name: cameraevents
        build: .
        # env_file:
        #   - .env
        environment:
            - MAX_WORKERS=1