version: '3.3'
services:
    cameraevents:
        volumes:
            - '/volume1/docker/cameraevents/userdb.db:/app/userdb.db'
            - '/volume1/docker/cameraevents/logs/:/app/logs/'
        ports:
            - '18088:80'
        network_mode: web
        container_name: cameraevents
        build: .
        # env_file:
        #   - .env
        environment:
            - MAX_WORKERS=1
            - UVICORN_APP_VERSION="0.0.2"
            - UVICORN_FRIGATE_BASEURL=$UVICORN_FRIGATE_BASEURL
            - UVICORN_SERET_KEY=$UVICORN_SERET_KEY
            - UVICORN_DATABASE_URL=$UVICORN_DATABASE_URL
            - UVICORN_DOCS_URL=$UVICORN_DOCS_URL