name: Create and publish a Docker image

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Delete Package Versions
        uses: actions/delete-package-versions@v4.1.1
        with:
          package-name: camera-events-service
          # Type of package. Can be one of container, maven, npm, nuget, or rubygems.
          package-type: container
          # Number of versions to delete starting with the oldest version. Defaults to 1.
          num-old-versions-to-delete: 0
          # Number of versions to keep starting with the latest version By default keeps no version. To delete all versions set this as 0.
          min-versions-to-keep: 2
          # Regex pattern for package versions to ignore. Defaults to delete all versions.
          token: # optional, default is ${{ github.token }}
